### ISSUE TITLE
New Android Auth SDK available

### ISSUE THREAD

**Issue by mediaController** [KaustubhPatange/Unofficial-Spotify-SDK#1]
https://github.com/KaustubhPatange/Unofficial-Spotify-SDK/blob/41427ad1032742ec2cd95f3ab200b5f19e76a6ea/app/spotifyapi/build.gradle#L49

There is now spotify-auth-release-1.2.1.aar

**Comment by KaustubhPatange** [comment]
Implemented spotify-auth-1.2.3 version
